# Generated by Django 4.2.11 on 2024-03-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_reciperequirement_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='menu_items',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit_price',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Price per unit'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='reciperequirement',
            name='quantity',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
