# Generated by Django 4.2.11 on 2024-03-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_menuitem_menu_items_remove_purchase_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit_price',
            field=models.FloatField(verbose_name='Price per unit'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='reciperequirement',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
